### ISSUE TITLE
Test report Debian GNU/Linux 12 bookworm (x86-64)

### ISSUE THREAD

**Issue by tooold2rock-n-roll** [ubaldot/experiments#2]
When I sourced the new script, it gave a warning about configuration I already had in my vimrc:
```
Error detected while processing /experiments/termdebug9.vim:
line  146:
E174: Command already exists: add ! to replace it: Termdebug StartDebug(<bang>0, <f-args>)
```

This is a screenshot after invoking _:Termdebug_
![Screenshot from 2024-05-16 08-52-20](https://github.com/ubaldot/experiments/assets/36848793/fff7406e-655a-4f79-993f-5f797da4b6eb)

And this is a screenshot of the example program after running:
![Screenshot from 2024-05-16 09-03-35](https://github.com/ubaldot/experiments/assets/36848793/ee9cd6a0-b787-417a-b598-bea216abbd17)

And this is a screenshot of the example code running:
![Screenshot from 2024-05-16 09-21-33](https://github.com/ubaldot/experiments/assets/36848793/f2dbc5c6-e0c2-4f69-8f55-c967af627df1)

So it seams to be running just fine!

**Comment by ubaldot** [comment]
OK! Regarding the first issue I think it is due to you already have loaded the legacy vimscript written temdebug. But super that it is working on Debian! Many thanks for the support!

I am actually finishing to vim9-ing the source code plus doing some additional cosmetic adjustments here and there in the other branch. For example, I noticed that if a user has a crowded statusline, the interface will look like a Xmas tree when running :Termdebug...

**Comment by ubaldot** [comment]
Hi there! The Termdebug plugin has finally ported to Vim9 and it is now in the official distribution. :) 
A number of improvements are also undergoing. On top of that, I also extended termdebug with a plugin for embedded systems: https://github.com/ubaldot/vim-microdebugger It is still in early stages and it does not work super well with Windows, but that is the way it is. 

At this point I think that I will shutoff this repo. Thanks for helping out with your tests and feel free to test the Vim9 version of termdebug included in the Vim distribution!

**Comment by tooold2rock-n-roll** [comment]
Very very very cool! I will update vim from source and check it out.

One thing I don't understand, why your version (the one I tested) has more division on screen with more useful information??

I researched this and tried alternative configurations for termdebug and even installed one from Debian's package manager to be sure I was using the latest one, but I can't seam to find the reason.....

Will it be like this in the latest Vim??

**Comment by ubaldot** [comment]
> One thing I don't understand, why your version (the one I tested) has more division on screen with more useful information??

It should be the same. You should use the `g:termdebug_config` dictionary to tell Termdebug what to show. Take a look at `:h termdebug_config`.  ;-) Let me know!

**Comment by tooold2rock-n-roll** [comment]
I see.....
hum, I completely misunderstood that section when reading the first time......

What values did you use to create that exact result?
I looked at the plugin and found only the points where it reads form the list, the test *.vim files use some but nothing that I recognize from the help.

**Comment by ubaldot** [comment]
Here is an example

```
packadd! termdebug

g:termdebug_config = {}
g:termdebug_config['variables_window'] = true
g:termdebug_config['variables_window_height'] = 15
g:termdebug_config['disasm_window'] = true
g:termdebug_config['disasm_window_height'] = 15
```

You can add them to your .`vimrc` and play with the heights of the various windows. There is also a `g:termdebug_config['wide']` parameter that you can play around.

If your `.vimrc` is written in legacy language, add a `let` in front of the lines starting with `g:` . At the moment the layout is kinda fixed, but we are working on a PR so you can shuffle the windows freely on your screen. In the future we plan to give the opportunity of placing this info into popup menus. 

Let me know if you need more help!

**Comment by tooold2rock-n-roll** [comment]
Ok, it's working now.
The thing is, you have to choose if you are going to use the new _termdebug_config_ or the old format.

I kept _g:termdebug_wide = 1_ and it was messing up the result.

Thanks for your assistance   o/
